from data_structure.link_list import ListNode, build_link_list, flatten_link_list
from data_structure.binary_tree import TreeNode, build_binary_tree, flatten_binary_tree
from data_structure.data_structure_printer import ds_print
